### ISSUE TITLE
Where to contribute?

### ISSUE THREAD

**Issue by aaemnnosttv** [vanderwijk/custom-post-widget#1]
Hi there!

I have some enhancements I would like to contribute to the plugin, but this repository is not up to date with the latest version of the plugin. (currently 2.8.5)

Does this project live in a different repository now?  Are you open to contributions?

**Comment by vanderwijk** [comment]
After the initial upload of the plugin to GitHub two years ago I found out that I still needed to use SVN to push my commits to the WordPress.org plugin directory and never used GitHub again...

Because I am always happy if to receive plugin contributions I have updated the GitHub repository to v2.8.5 for you. So yes, I am open to contributions and look forward to your suggestions. Note that I cannot guarantee beforehand that all your changes will be incorporated in the plugin.

**Comment by aaemnnosttv** [comment]
Hey there,

Thanks a lot for updating the repo, I haven't forgotten about this and still want to offer some improvements.  Just wanted to ask if you could sync the repository again if there have been any updates since you did last.

Thank you!

**Comment by vanderwijk** [comment]
I have not made any changes to the plugin code since I last synced it to Github so it is safe to publish your proposed changes!
